server:
  port: 9095
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Password@123
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
app:  
 props:
  usercreation: user created successfully
  loginsucess : Login Successfully
  userretrieve: user Retrieved Successfully 
  usersretrieve: All users Retrieved Successfully
  userupdate: user Updated Successfully.
  userdelete: user Deleted Successfully.
  rolecreation: Role created successfully
  roleretrieve: Role Retrieved Successfully 
  rolesretrieve: All Roles Retrieved Successfully
  roleupdate: role Updated Successfully.
  roledelete: role Deleted Successfully.  
  alreadyregister: You already Registered with 
  rolenotfound : Role Not Found with Id-
  usernotfound : User Not Found with Id-    
