server:
  port: 9007
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Password@123
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
cart:  
 props:
  placeorder: Order Placed successfully
  ordersretrieve: Orders Retrieved Successfully 
  orderupdate: Order Updated Successfully.
  orderdelete: Order Deleted Successfully.
  ordernotfound : Order Not Found with Id
